version: 2

install_elixir: &install_elixir
  run:
    name: Install Elixir
    command: |
      wget https://repo.hex.pm/builds/elixir/v$ELIXIR_VERSION.zip
      unzip -d /usr/local/elixir v$ELIXIR_VERSION.zip
      echo 'export PATH=/usr/local/elixir/bin:$PATH' >> $BASH_ENV

install_hex_rebar: &install_hex_rebar
  run:
    name: Install hex and rebar
    command: |
      mix local.hex --force
      mix local.rebar --force

defaults: &defaults
  working_directory: ~/repo

jobs:
  build_elixir_1_10_otp_23:
    docker:
      - image: erlang:23.0.1
        environment:
          ELIXIR_VERSION: 1.10.3-otp-23
          LC_ALL: C.UTF-8
    <<: *defaults
    steps:
      - checkout
      - <<: *install_elixir
      - <<: *install_hex_rebar
      - restore_cache:
          keys:
            - v1-mix-cache-{{ checksum "mix.lock" }}
      - run: mix deps.get
      - run: mix test --exclude distillery
      - run: mix format --check-formatted
      - run: mix docs
      - run: mix hex.build
      - run: mix dialyzer
      - save_cache:
          key: v1-mix-cache-{{ checksum "mix.lock" }}
          paths:
            - _build
            - deps

  build_elixir_1_10_otp_22:
    docker:
      - image: erlang:22.3.4.1
        environment:
          ELIXIR_VERSION: 1.10.3-otp-22
          LC_ALL: C.UTF-8
    <<: *defaults
    steps:
      - checkout
      - <<: *install_elixir
      - <<: *install_hex_rebar
      - run: mix deps.get
      - run: mix test --exclude elixir_release

  build_elixir_1_9_otp_22:
    docker:
      - image: erlang:22.2
        environment:
          ELIXIR_VERSION: 1.9.4-otp-22
          LC_ALL: C.UTF-8
    <<: *defaults
    steps:
      - checkout
      - <<: *install_elixir
      - <<: *install_hex_rebar
      - run: mix deps.get
      - run: mix test --exclude elixir_release

  build_elixir_1_8_otp_22:
    docker:
      - image: erlang:22.0
        environment:
          ELIXIR_VERSION: 1.8.2-otp-22
          LC_ALL: C.UTF-8
    <<: *defaults
    steps:
      - checkout
      - <<: *install_elixir
      - <<: *install_hex_rebar
      - run: mix deps.get
      - run: mix test --exclude elixir_release

  build_elixir_1_7_otp_21:
    docker:
      - image: erlang:21.3
        environment:
          ELIXIR_VERSION: 1.7.4-otp-21
          LC_ALL: C.UTF-8
    <<: *defaults
    steps:
      - checkout
      - <<: *install_elixir
      - <<: *install_hex_rebar
      - run: mix deps.get
      - run: mix test --exclude elixir_release

workflows:
  version: 2
  build_test:
    jobs:
      - build_elixir_1_10_otp_23
      - build_elixir_1_10_otp_22
      - build_elixir_1_9_otp_22
      - build_elixir_1_8_otp_22
      - build_elixir_1_7_otp_21
